---
title: "Datasets"
author: "August E. G. Mikkelsen"
date: "`r Sys.Date()`"
output: pdf_document
header-includes:
  - \usepackage{xcolor}
---

```{r Load,  eval=TRUE, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(stringr)
library(future)
library(purrr)
library(furrr)

vurderingsejendomme <- readRDS("vurderingsejendomme.rds")
ejendomssalg <- readRDS("ejendomssalg.rds")
grundsalg <- readRDS("grundsalg.rds")

```

# Beskrivelse
Her gennemgås step-by-step processen til at generere det endelige datasæt anvendt i modellerne. 


## 1. Single family houses 

```{r PCL, eval=TRUE, echo=TRUE, warning=FALSE, results = 'hide'}

#Kun én vurderingsejendom, enhed, delgrund og bygning  
ejendomssalg <- ejendomssalg %>%
                add_count(vurderingsejendom_id_ice, df_virkningstid, name = "n_vurd") %>%
                add_count(delgrund.delgrund_ids, df_virkningstid, name = "n_delgrund") %>%
                add_count(enhed.enhed_id_ice, df_virkningstid, name = "n_enhed") %>%
                add_count(bygning.bygning_id_ice, df_virkningstid, name = "n_bygning") %>%
                filter(n_vurd == 1, n_delgrund == 1, n_enhed == 1, n_bygning == 1) %>%
                select(-n_vurd, -n_delgrund, -n_enhed, -n_bygning)

vurderingsejendomme <- vurderingsejendomme %>%
                       add_count(vurderingsejendom_id_ice, df_virkningstid, name = "n_vurd") %>%
                       add_count(delgrund.delgrund_ids, df_virkningstid, name = "n_delgrund") %>%
                       add_count(enhed.enhed_id_ice, df_virkningstid, name = "n_enhed") %>%
                       add_count(bygning.bygning_id_ice, df_virkningstid, name = "n_bygning") %>%
                       filter(n_vurd == 1, n_delgrund == 1, n_enhed == 1, n_bygning == 1) %>%
                       select(-n_vurd, -n_delgrund, -n_enhed, -n_bygning)

grundsalg <- grundsalg %>%
             add_count(vurderingsejendom_id_ice, df_virkningstid, name = "n_vurd") %>%
             add_count(delgrund.delgrund_ids, df_virkningstid, name = "n_delgrund") %>%
             filter(n_vurd == 1, n_delgrund == 1) %>%
             select(-n_vurd, -n_delgrund)


#Fjern bunkesalg
ejendomssalg <- ejendomssalg %>%
                group_by(salg.koebsdato, salg.anmeldelseidentifikator, salg.ialtkoebesum, vurinfo.kommunenummer) %>%
                filter(n() == 1) %>%
                ungroup()

grundsalg <- grundsalg %>%
             group_by(salg.koebsdato, salg.anmeldelseidentifikator, salg.ialtkoebesum, vurinfo.kommunenummer) %>%
             filter(n() == 1) %>%
             ungroup()


#Berig delgrunde med plandata for deljordstykker. 

## fold deljordstykker ud
ejendomssalg <- udtraek_element(data = ejendomssalg,
                                col = "delgrund.deljordstykke",
                                keep_cols = names(ejendomssalg))

vurderingsejendomme <- udtraek_element(data = vurderingsejendomme,
                                       col = "delgrund.deljordstykke",
                                       keep_cols = names(vurderingsejendomme))


grundsalg <- udtraek_element(data = grundsalg,
                             col = "delgrund.deljordstykke",
                             keep_cols = names(grundsalg))



## fold plandata ud
ejendomssalg <- udtraek_element(data = ejendomssalg,
                                col = "deljordstykke.plandata",
                                keep_cols = names(ejendomssalg),
                                names_sep = "_")


vurderingsejendomme <- udtraek_element(data = vurderingsejendomme,
                                       col = "deljordstykke.plandata",
                                       keep_cols = names(vurderingsejendomme),
                                       names_sep = "_")


grundsalg <- udtraek_element(data = grundsalg,
                             col = "deljordstykke.plandata",
                             keep_cols = names(grundsalg),
                             names_sep = "_")


#Standard PCL-ejendomme
ejendomssalg_pcl <- ejendomssalg %>%
                    filter(bygning.bygningsanvendelse %in% c(120,121,122,130,131,132),
                           enhed.enhedsanvendelse %in% c(120,121,122,130,131,132),
                           salg.ejendomkategori == "EjendomKategoriEnfamiliesejendom",
                           !salg.flereejendommeindikator,
                           is.na(salg.bygningsforholdkode),
                           vurinfo.vurbenyttelseskode == "01", #Standard beboelse
                           vurinfo.antal_sfer == 1,
                           vurinfo.antal_bfer == 1,
                           is.na(bygning.ejerforholdskode), 
                           bygning.samlet_erhvervsareal == 0,
                           enhed.areal_til_erhverv == 0,
                           enhed.antal_vaerelser_til_erhverv == 0,
                           bygning.andetareal == 0,
                           enhed.boligtype == "1",
                           enhed.toiletforhold == "T",
                           enhed.badeforhold == "V",
                           enhed.koekkenforhold == "E",
                           delgrund.enheder_per_delgrund == 1,
                           delgrund.jordstykker_per_delgrund == 1,
                           delgrund.deljordstykker_per_delgrund == 1,
                           delgrund.beskyttelseslinier_andel == 0,
                           deljordstykke.areal_beskyttet == 0,
                           deljordstykke.andel_beskyttet == 0,
                           delgrund.samlet_sommerhuszoneareal == 0,
                           delgrund.samlet_udenzoneareal == 0,
                           deljordstykke.generelanvendelseskategori == 11,
                           deljordstykke.plandata_plandata.specifikanvendelseskategori %in% c("1100", "1110", "1120"),
                           is.na(deljordstykke.plandata_plandata.udstykstoerrelse) | deljordstykke.plandata_plandata.udstykstoerrelse >= 200 & deljordstykke.plandata_plandata.udstykstoerrelse <= 1200,
                           is.na(deljordstykke.plandata_plandata.maksbebygpct) | deljordstykke.plandata_plandata.maksbebygpct >= 20 & deljordstykke.plandata_plandata.maksbebygpct <= 80,
                           is.na(deljordstykke.plandata_plandata.maaikkeudstykkes))

vurderingsejendomme_pcl <- vurderingsejendomme %>%
                           filter(bygning.bygningsanvendelse %in% c(120,121,122,130,131,132),
                                  enhed.enhedsanvendelse %in% c(120,121,122,130,131,132),
                                  vurinfo.vurbenyttelseskode == "01", #Standard beboelse
                                  vurinfo.antal_sfer == 1,
                                  vurinfo.antal_bfer == 1,
                                  is.na(bygning.ejerforholdskode), 
                                  bygning.samlet_erhvervsareal == 0,
                                  enhed.areal_til_erhverv == 0,
                                  enhed.antal_vaerelser_til_erhverv == 0,
                                  bygning.andetareal == 0,
                                  enhed.boligtype == "1",
                                  enhed.toiletforhold == "T",
                                  enhed.badeforhold == "V",
                                  enhed.koekkenforhold == "E",
                                  delgrund.enheder_per_delgrund == 1,
                                  delgrund.jordstykker_per_delgrund == 1,
                                  delgrund.deljordstykker_per_delgrund == 1,
                                  delgrund.beskyttelseslinier_andel == 0,
                                  deljordstykke.areal_beskyttet == 0,
                                  deljordstykke.andel_beskyttet == 0,
                                  delgrund.samlet_sommerhuszoneareal == 0,
                                  delgrund.samlet_udenzoneareal == 0,
                                  deljordstykke.generelanvendelseskategori == 11,
                                  deljordstykke.plandata_plandata.specifikanvendelseskategori %in% c("1100", "1110", "1120"),
                                  is.na(deljordstykke.plandata_plandata.udstykstoerrelse) | deljordstykke.plandata_plandata.udstykstoerrelse >= 200 & deljordstykke.plandata_plandata.udstykstoerrelse <= 1200,
                                  is.na(deljordstykke.plandata_plandata.maksbebygpct) | deljordstykke.plandata_plandata.maksbebygpct >= 20 & deljordstykke.plandata_plandata.maksbebygpct <= 80,
                                  is.na(deljordstykke.plandata_plandata.maaikkeudstykkes))

grundsalg_pcl <- grundsalg %>%
                 filter(salg.ejendomkategori == "EjendomKategoriUbebyggetgrund",
                        !salg.flereejendommeindikator,
                        is.na(salg.bygningsforholdkode),
                        vurinfo.vurbenyttelseskode == "09", #Ubebygget areal
                        vurinfo.antal_sfer == 1,
                        vurinfo.antal_bfer == 1,
                        delgrund.enheder_per_delgrund == 0,
                        delgrund.jordstykker_per_delgrund == 1,
                        delgrund.deljordstykker_per_delgrund == 1,
                        delgrund.beskyttelseslinier_andel == 0,
                        lengths(delgrund.alle_bygninger_paa_delgrunden) == 0,
                        deljordstykke.areal_beskyttet == 0,
                        deljordstykke.andel_beskyttet == 0,
                        delgrund.samlet_sommerhuszoneareal == 0,
                        delgrund.samlet_udenzoneareal == 0,
                        deljordstykke.generelanvendelseskategori == 11,
                        deljordstykke.plandata_plandata.specifikanvendelseskategori %in% c("1100", "1110", "1120"),
                        is.na(deljordstykke.plandata_plandata.udstykstoerrelse) | deljordstykke.plandata_plandata.udstykstoerrelse >= 200 & deljordstykke.plandata_plandata.udstykstoerrelse <= 1200,
                        is.na(deljordstykke.plandata_plandata.maksbebygpct) | deljordstykke.plandata_plandata.maksbebygpct >= 20 & deljordstykke.plandata_plandata.maksbebygpct <= 80,
                        is.na(deljordstykke.plandata_plandata.maaikkeudstykkes))



```



## 2. Data cleaning


```{r Cleaning,  eval=TRUE, echo=TRUE, warning=FALSE, results = 'hide'}

#Fjen NA'er for forskellige variable
ejendomssalg_pcl <- ejendomssalg_pcl %>%
                    filter(!is.na(vurinfo.adresse.koordinatoest),
                           !is.na(vurinfo.adresse.koordinatnord),
                           !is.na(salg.koebsdato),
                           !is.na(bygning.opfoerelsesaar),
                           !is.na(bygning.omtilbygningsaar),
                           !is.na(enhed.areal_til_beboelse),
                           !is.na(delgrund.registeret_areal_uden_vej),
                           !is.na(delgrund.zone),
                           !is.na(salg.ialtkoebesum),
                           !is.na(bygning.tagdaekningsmateriale),
                           !is.na(bygning.varmeinstallation),
                           !is.na(bygning.ydervaeggensmateriale),
                           !is.na(vurinfo.udsigtslaengde_hav),
                           !is.na(vurinfo.udsigtslaengde_soe),
                           !is.na(vurinfo.areal_samlet_skov))

vurderingsejendomme_pcl  <- vurderingsejendomme_pcl  %>%
                            filter(!is.na(vurinfo.adresse.koordinatoest),
                                   !is.na(vurinfo.adresse.koordinatnord),
                                   !is.na(bygning.opfoerelsesaar),
                                   !is.na(bygning.omtilbygningsaar),
                                   !is.na(enhed.areal_til_beboelse),
                                   !is.na(delgrund.registeret_areal_uden_vej),
                                   !is.na(delgrund.zone),
                                   !is.na(bygning.tagdaekningsmateriale),
                                   !is.na(bygning.varmeinstallation),
                                   !is.na(bygning.ydervaeggensmateriale),
                                   !is.na(vurinfo.udsigtslaengde_hav),
                                   !is.na(vurinfo.udsigtslaengde_soe),
                                   !is.na(vurinfo.areal_samlet_skov))

grundsalg_pcl <- grundsalg_pcl %>% filter(!is.na(vurinfo.adresse.koordinatoest),
                                          !is.na(vurinfo.adresse.koordinatnord),
                                          !is.na(salg.koebsdato),
                                          !is.na(vurinfo.registreretareal_fratrukket_vejareal),
                                          !is.na(delgrund.zone),
                                          !is.na(salg.ialtkoebesum),
                                          !is.na(vurinfo.udsigtslaengde_hav),
                                          !is.na(vurinfo.udsigtslaengde_soe),
                                          !is.na(vurinfo.areal_samlet_skov))


#Fjern forskellige abnormaliteter. Bla. ejendomme med vejarealer for at goere livet nemmere for os. 
ejendomssalg_pcl <- ejendomssalg_pcl %>%
                    filter(as.integer(format(as.Date(salg.koebsdato), "%Y")) >= bygning.opfoerelsesaar,
                           as.integer(format(as.Date(salg.koebsdato), "%Y")) >= bygning.omtilbygningsaar,
                           enhed.areal_til_beboelse == bygning.samlet_boligareal,
                           enhed.areal_til_beboelse > 0,
                           vurinfo.registreretareal_fratrukket_vejareal > 0,
                           delgrund.registeret_areal_uden_vej == vurinfo.registreretareal_fratrukket_vejareal,
                           delgrund.arealberegnet == vurinfo.registreretareal_fratrukket_vejareal,
                           deljordstykke.registreret_areal_uden_vej == vurinfo.registreretareal_fratrukket_vejareal,
                           deljordstykke.registreret_areal == vurinfo.registreretareal_fratrukket_vejareal,
                           deljordstykke.arealberegnetudenvej == vurinfo.registreretareal_fratrukket_vejareal,
                           deljordstykke.arealberegnet == vurinfo.registreretareal_fratrukket_vejareal) 

vurderingsejendomme_pcl <- vurderingsejendomme_pcl %>%
                           filter(enhed.areal_til_beboelse == bygning.samlet_boligareal,
                                  enhed.areal_til_beboelse > 0,
                                  vurinfo.registreretareal_fratrukket_vejareal > 0,
                                  delgrund.registeret_areal_uden_vej == vurinfo.registreretareal_fratrukket_vejareal,
                                  delgrund.arealberegnet == vurinfo.registreretareal_fratrukket_vejareal,
                                  deljordstykke.registreret_areal_uden_vej == vurinfo.registreretareal_fratrukket_vejareal,
                                  deljordstykke.registreret_areal == vurinfo.registreretareal_fratrukket_vejareal,
                                  deljordstykke.arealberegnetudenvej == vurinfo.registreretareal_fratrukket_vejareal,
                                  deljordstykke.arealberegnet == vurinfo.registreretareal_fratrukket_vejareal)

grundsalg_pcl <- grundsalg_pcl %>% 
                 filter(vurinfo.registreretareal_fratrukket_vejareal > 0,
                        delgrund.arealberegnet == vurinfo.registreretareal_fratrukket_vejareal,
                        deljordstykke.registreret_areal_uden_vej == vurinfo.registreretareal_fratrukket_vejareal,
                        deljordstykke.registreret_areal == vurinfo.registreretareal_fratrukket_vejareal,
                        deljordstykke.arealberegnetudenvej == vurinfo.registreretareal_fratrukket_vejareal,
                        deljordstykke.arealberegnet == vurinfo.registreretareal_fratrukket_vejareal)


#Udvælg ejendomme med standardegenskaber. For at gøre det simpelt udvælges kun de mest hyppige enhedstyper, tagtyper osv for salgene. 
round(prop.table(table(ejendomssalg_pcl$enhed.enhedsanvendelse)), 3) * 100 #120'ere og 130'ere udgør 98%, så disse vælges
round(prop.table(table(ejendomssalg_pcl$bygning.varmeinstallation)), 3) * 100 #1, 2, 5 og 7 er klart mest fremtrædende så disse vælges
round(prop.table(table(ejendomssalg_pcl$bygning.tagdaekningsmateriale)), 3) * 100 #1, 2, 3, 4 og 5 er mest fremtrædende så disse vælges
round(prop.table(table(ejendomssalg_pcl$bygning.ydervaeggensmateriale)), 3) * 100 #1, 2 og 5 er mest fremtrædende så disse vælges
round(prop.table(table(ejendomssalg_pcl$enhed.antal_vaerelser)), 3) * 100 #Vælg 2, 3, 4, 5, 6, 7 og 8 svarende til alle med en procentdel over 1
round(prop.table(table(ejendomssalg_pcl$enhed.antal_badevaerelser)), 3) * 100 #Vælg 1, 2, og 3 svarende til alle med en procentdel over 1
round(prop.table(table(ejendomssalg_pcl$bygning.antal_etager)), 3) * 100 #Vælg 1 og 2 svarende til alle med en procentdel over 1


ejendomssalg_pcl <- ejendomssalg_pcl %>%
                    filter(salg.ialtkoebesum >= 1e+5 & salg.ialtkoebesum <= 1.5e+7,
                           vurinfo.registreretareal_fratrukket_vejareal <= 3000,
                           vurinfo.registreretareal_fratrukket_vejareal >= 100,
                           enhed.areal_til_beboelse <= 400,
                           enhed.areal_til_beboelse >= 50,
                           bygning.opfoerelsesaar >= 1900,
                           delgrund.zone %in% c(1,2), #kun byzone og landzone
                           enhed.enhedsanvendelse %in% c(120,130),
                           bygning.bygningsanvendelse %in% c(120,130), 
                           bygning.varmeinstallation %in% c(1,2,5,7),
                           bygning.tagdaekningsmateriale %in% c(1,2,3,4,5),
                           bygning.ydervaeggensmateriale %in% c(1,2,5), 
                           enhed.antal_vaerelser %in% c(2,3,4,5,6,7,8,9,10),
                           enhed.antal_badevaerelser %in% c(1,2,3),
                           bygning.antal_etager %in% c(1,2))


vurderingsejendomme_pcl <- vurderingsejendomme_pcl %>%
                           filter(vurinfo.registreretareal_fratrukket_vejareal <= 3000,
                                  vurinfo.registreretareal_fratrukket_vejareal >= 100,
                                  enhed.areal_til_beboelse <= 400,
                                  enhed.areal_til_beboelse >= 50,
                                  bygning.opfoerelsesaar >= 1900,
                                  delgrund.zone %in% c(1,2), #kun byzone og landzone
                                  enhed.enhedsanvendelse %in% c(120,130),
                                  bygning.bygningsanvendelse %in% c(120,130), 
                                  bygning.varmeinstallation %in% c(1,2,5,7),
                                  bygning.tagdaekningsmateriale %in% c(1,2,3,4,5),
                                  bygning.ydervaeggensmateriale %in% c(1,2,5), 
                                  enhed.antal_vaerelser %in% c(2,3,4,5,6,7,8,9,10),
                                  enhed.antal_badevaerelser %in% c(1,2,3),
                                  bygning.antal_etager %in% c(1,2))


grundsalg_pcl <- grundsalg_pcl %>% filter(salg.ialtkoebesum >= 1e+5 & salg.ialtkoebesum <= 1.5e+7,
                                          vurinfo.registreretareal_fratrukket_vejareal <= 3000,
                                          vurinfo.registreretareal_fratrukket_vejareal >= 100,
                                          delgrund.zone %in% c(1,2)) #kun byzone og landzone
                              


#Fjern ejendomme med salgsflag 
ejendomssalg_pcl <- ejendomssalg_pcl %>% 
                    filter(!str_detect(salg_flag, "120|121|122|123|124|125|127|128|129|130|131|132|150|151|153|154|155|156|202|203|204"))

grundsalg_pcl <- grundsalg_pcl %>% 
                 filter(!str_detect(salg_flag, "120|121|122|123|124|125|127|128|129|130|131|132|150|151|153|154|155|156|202|203|204"))


#Der vælges specifikanvendelseskategori med prioritet i rækkefølgen 1110, 1120 og 1100 
ejendomssalg_pcl <- ejendomssalg_pcl %>%
                    group_by(vurderingsejendom_id_ice, salg.koebsdato) %>%
                    arrange(desc(match(deljordstykke.plandata_plandata.specifikanvendelseskategori, c("1100", "1120", "1110"))), .by_group = TRUE) %>%
                    slice(1) %>%
                    ungroup()

vurderingsejendomme_pcl <- vurderingsejendomme_pcl %>%
                           group_by(vurderingsejendom_id_ice) %>%
                           arrange(desc(deljordstykke.plandata_plandata.specifikanvendelseskategori == "1110"), .by_group = TRUE) %>%
                           slice(1) %>%
                           ungroup()

grundsalg_pcl <- grundsalg_pcl %>%
                 group_by(vurderingsejendom_id_ice, salg.koebsdato) %>%
                 arrange(desc(deljordstykke.plandata_plandata.specifikanvendelseskategori == "1110"), .by_group = TRUE) %>%
                 slice(1) %>%
                 ungroup()


#Check at datasæt er unikke paa forskellige id-niveauer

##ejendomssalg
stopifnot(nrow(ejendomssalg_pcl %>% distinct(vurderingsejendom_id_ice, salg.koebsdato)) == nrow(ejendomssalg_pcl))
stopifnot(nrow(ejendomssalg_pcl %>% distinct(enhed.enhed_id_ice, salg.koebsdato)) == nrow(ejendomssalg_pcl))
stopifnot(nrow(ejendomssalg_pcl %>% distinct(delgrund.delgrund_ids, salg.koebsdato)) == nrow(ejendomssalg_pcl))
stopifnot(nrow(ejendomssalg_pcl %>% distinct(bygning.bygning_id_ice, salg.koebsdato)) == nrow(ejendomssalg_pcl))

##vurderingsejendomme
stopifnot(nrow(vurderingsejendomme_pcl %>% distinct(vurderingsejendom_id_ice)) == nrow(vurderingsejendomme_pcl))
stopifnot(nrow(vurderingsejendomme_pcl %>% distinct(enhed.enhed_id_ice)) == nrow(vurderingsejendomme_pcl))
stopifnot(nrow(vurderingsejendomme_pcl %>% distinct(delgrund.delgrund_ids)) == nrow(vurderingsejendomme_pcl))

##grundsalg
stopifnot(nrow(grundsalg_pcl %>% distinct(vurderingsejendom_id_ice, salg.koebsdato)) == nrow(grundsalg_pcl))
stopifnot(nrow(grundsalg_pcl %>% distinct(delgrund.delgrund_ids, salg.koebsdato)) == nrow(grundsalg_pcl))
stopifnot(nrow(grundsalg_pcl %>% distinct(deljordstykke.deljordstykke_id_ice, salg.koebsdato)) == nrow(grundsalg_pcl))

```

## 3. Final dataset

```{r Dataset, eval=TRUE, echo=TRUE, warning=FALSE, results = 'hide'}
#join data frames of property sales and valuation properties
ejendomssalg_pcl <- ejendomssalg_pcl %>% mutate(type = "Property sale")
vurderingsejendomme_pcl <- vurderingsejendomme_pcl %>% mutate(type = "Property")
grundsalg_pcl <- grundsalg_pcl %>% mutate(type = "Lot sale")
dataset <- bind_rows(ejendomssalg_pcl, vurderingsejendomme_pcl, grundsalg_pcl)


#variables to select
variables <- c(id = "vurinfo.vurderingsejendom_id",
               sales_date = "salg.koebsdato",
               municipality = "kommune_navn",
               province = "landsdel_navn",
               region = "region_navn",
               municipality_type = "kommunegruppe",
               zone = "delgrund.zone",
               sales_price = "salg.ialtkoebesum",
               house_type = "enhed.enhedsanvendelse",
               living_space = "enhed.areal_til_beboelse",
               number_of_rooms = "enhed.antal_vaerelser",
               number_of_floors = "bygning.antal_etager",
               number_of_bathrooms = "enhed.antal_badevaerelser",
               lot_size = "vurinfo.registreretareal_fratrukket_vejareal",
               year_built = "bygning.opfoerelsesaar",
               year_rebuilt = "bygning.omtilbygningsaar",
               roof_type = "bygning.tagdaekningsmateriale",
               heating_type = "bygning.varmeinstallation",
               wall_type = "bygning.ydervaeggensmateriale",
               coordinate_east = "vurinfo.adresse.koordinatoest",
               coordinate_north = "vurinfo.adresse.koordinatnord",
               coast_distance = "vurinfo.afstand_kyst",
               lake_distance = "vurinfo.afstand_stor_soe",
               stream_distance = "vurinfo.afstand_stort_vandloeb",
               road_distance = "vurinfo.afstand_naermeste_trafikvejgennemfart_trafikfordeling",
               highway_distance = "vurinfo.afstand_motorvej_motortrafikvej",
               train_station_distance = "vurinfo.afstand_station_any",
               railway_distance = "vurinfo.afstand_jernbane_any",
               windturbine_distance = "vurinfo.afstand_vindmoelle_any",
               ocean_view = "vurinfo.udsigtslaengde_hav",
               lake_view = "vurinfo.udsigtslaengde_soe",
               forest_size = "vurinfo.areal_samlet_skov",
               maximum_coverage_percentage = "deljordstykke.plandata_plandata.maksbebygpct",
               subdivision_size = "deljordstykke.plandata_plandata.udstykstoerrelse",
               zoning_use_category = "deljordstykke.plandata_plandata.specifikanvendelseskategori",
               zoning_use_categories = "delgrund.unikke_plananvendelser",
               type = "type")

dataset <- dataset %>%
           rename(!!!setNames(variables, names(variables))) %>%
           select(names(variables))


#lav id om til standard range
id_map <- match(dataset$id, unique(dataset$id))
dataset$id <- id_map

#omdoeb zone (1=byzone,2=landzone)
dataset$zone[dataset$zone == 1] = "Urban"
dataset$zone[dataset$zone == 2] = "Rural"

#omdoeb municipality_type
dataset$municipality_type[dataset$municipality_type == "Hovedstadskommune"] = "Capital"
dataset$municipality_type[dataset$municipality_type == "Landkommune"] = "Rural"
dataset$municipality_type[dataset$municipality_type == "Oplandskommune"] = "Commuter"
dataset$municipality_type[dataset$municipality_type == "Provinsbykommune"] = "Provincial"
dataset$municipality_type[dataset$municipality_type == "Storbykommune"] = "Large city"

#omdoeb hustype
dataset$house_type[dataset$house_type == 120] = "Detached"
dataset$house_type[dataset$house_type == 130] = "Semi-detached"

#omdoeb tagtyper
dataset$roof_type[(dataset$roof_type %in% c(1,2))] = "Roofing felt"
dataset$roof_type[dataset$roof_type == 3] = "Fiber cement"
dataset$roof_type[dataset$roof_type == 4] = "Roofing tiles"
dataset$roof_type[dataset$roof_type == 5] = "Tiles"

#omdoeb varmekilder
dataset$heating_type[dataset$heating_type == 1] = "District heating"
dataset$heating_type[dataset$heating_type == 2] = "Central heating"
dataset$heating_type[dataset$heating_type == 5] = "Heat pump"
dataset$heating_type[dataset$heating_type == 7] = "Electric heating"

#omdoeb vaegtyper
dataset$wall_type[dataset$wall_type == 1] = "Brick"
dataset$wall_type[dataset$wall_type == 2] = "Lightweight concrete"
dataset$wall_type[dataset$wall_type == 5] = "Wood"


#lav ombygningsaar til NA (lidt fjollet, men for at alle imputationer virker på NA-værdier)
dataset$year_rebuilt[which(dataset$year_rebuilt==0)] = NA


#save file
saveRDS(dataset, "dataset.rds")

```

